image: node:12

workflow:
  rules:
    - if: $CI_MERGE_REQUEST_ID
    - if: $CI_COMMIT_TAG

before_script:
  - npm -v
  - node -v
  - npm i -s

stages:
  - test
  - publish

lint:
  stage: test
  script:
    - npm run lint
  rules:
    - if: '$CI_COMMIT_TAG == null'
      when: always

test:
  stage: test
  script:
    - npm test
  rules:
    - if: '$CI_COMMIT_TAG == null'
      when: always

development:
  stage: publish
  script:
    - npm run build
    - touch ".npmrc"
    - echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" >> "/builds/noname.team/libraries/vk-chat-bot/.npmrc"
    - npm publish --access public
  rules:
    - if: '$CI_COMMIT_TAG =~ /^v\d\.\d\.\d\-dev\-.+$/'
      when: always

production:
  stage: publish
  script:
    - npm run build
    - touch ".npmrc"
    - echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" >> "/builds/noname.team/libraries/vk-chat-bot/.npmrc"
    - npm publish --access public
  rules:
    - if: '$CI_COMMIT_TAG =~ /^v\d\.\d\.\d$/'
      when: manual

after_script:
  - rm -rf node_modules package-lock.json .npmrc build
