image: node:12

workflow:
  rules:
    - if: $CI_MERGE_REQUEST_ID
    - if: $CI_COMMIT_TAG

before_script:
  - echo $CI_COMMIT_TAG
  - npm -v
  - node -v
  - npm i -s

stages:
  - test
  - publish

lint:
  stage: test
  script:
    - npm run lint
  rules:
    - if: '$CI_COMMIT_TAG == null'
      when: always

test:
  stage: test
  script:
    - npm test
  rules:
    - if: '$CI_COMMIT_TAG == null'
      when: always

build:
  stage: publish
  script:
    - npm run build
    - npm pack
    - mkdir artifacts
    - mv *.tgz artifacts/
  rules:
    - if: '$CI_COMMIT_TAG != null'
      when: on_success
  artifacts:
    paths: ['artifacts']
    expire_in: 2 days

development:
  stage: publish
  image: python:latest
  script:
    - pip install awscli
    - aws --endpoint-url=https://storage.yandexcloud.net s3 cp ./artifacts/ s3://dev-bucket-packages/ --recursive --exclude "*" --include "*.tgz"
  rules:
    - if: '$CI_COMMIT_TAG =~ /^v\d\.\d\.\d\-dev\-.+$/'
      when: on_success

production:
  stage: publish
  script:
    - touch ".npmrc"
    - echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" >> "/builds/noname.team/libraries/vk-chat-bot/.npmrc"
    - npm publish --access public
  rules:
    - if: '$CI_COMMIT_TAG =~ /^v\d\.\d\.\d$/'
      when: manual

after_script:
  - rm -rf node_modules package-lock.json .npmrc build
